// Builds the app into dist/ — everything static, no server needed afterwards.
//
// The only real work is bundling the npm libraries into vendor/bundle.js. Two of them
// need help: wasm-zstd is written for Node and reaches for Buffer, fs and path, and its
// WebAssembly has to sit next to index.html because that is where the browser looks.
import * as esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";

const OUT = "dist";
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(`${OUT}/vendor`, { recursive: true });

// The bundle is written into vendor/ rather than straight into dist/, so that src/
// resolves the same whether you open the repo directly or serve dist/. Without that,
// the app and its own tests only work after a build, which is a trap.
await esbuild.build({
  entryPoints: ["vendor/entry.js"],
  bundle: true,
  format: "esm",
  platform: "browser",
  minify: true,
  outfile: "vendor/bundle.js",
  alias: { fs: "./vendor/node-stub.js", path: "./vendor/node-stub.js" },
  inject: ["./vendor/buffer-shim.js"],
  loader: { ".wasm": "file" },
  assetNames: "[name]",
  logLevel: "info",
});

// Emscripten resolves its .wasm against the page, not the script, so it goes at the
// root — of dist/, of the repo, and beside the test page, all for the same reason.
for (const dir of [".", "test"]) fs.copyFileSync("vendor/wasm-zstd.wasm", `${dir}/wasm-zstd.wasm`);

const copy = (src) => {
  const stat = fs.statSync(src);
  if (stat.isDirectory()) {
    fs.mkdirSync(path.join(OUT, src), { recursive: true });
    for (const e of fs.readdirSync(src)) copy(path.join(src, e));
  } else {
    fs.mkdirSync(path.join(OUT, path.dirname(src)), { recursive: true });
    fs.copyFileSync(src, path.join(OUT, src));
  }
};
for (const f of ["index.html", "render.html", "token-check.html", "app.css", "config.json", "wasm-zstd.wasm", "src", "templates", "vendor"]) copy(f);

// A service worker turns the page into an installable app that still works with no
// internet, which matters in a paddock at Silverstone.
const files = [];
const walk = (dir) => {
  for (const e of fs.readdirSync(dir)) {
    const p = path.join(dir, e);
    if (fs.statSync(p).isDirectory()) walk(p);
    else files.push("./" + path.relative(OUT, p).split(path.sep).join("/"));
  }
};
walk(OUT);
fs.writeFileSync(`${OUT}/sw.js`, `// generated by build.mjs
const CACHE = "log-studio-${Date.now().toString(36)}";
const FILES = ${JSON.stringify(files.concat(["./"]), null, 1)};
self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("fetch", (e) => {
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) return; // GitLab templates always go to the network
  e.respondWith(fetch(e.request).catch(() => caches.match(e.request).then((r) => r ?? caches.match("./index.html"))));
});
`);
fs.writeFileSync(`${OUT}/manifest.webmanifest`, JSON.stringify({
  name: "TBRe Log Studio", short_name: "Log Studio", start_url: "./", display: "standalone",
  background_color: "#ffffff", theme_color: "#105bab",
  description: "Watch and export TBRe autonomous runs from .mcap logs.",
}, null, 2));
fs.writeFileSync(`${OUT}/.nojekyll`, "");
console.log(`built ${files.length} files into ${OUT}/`);
