// generated by build.mjs
const CACHE = "log-studio-mty4y6j4";
const FILES = [
 "./app.css",
 "./config.json",
 "./index.html",
 "./render.html",
 "./src/export/encode.js",
 "./src/jobs.js",
 "./src/main.js",
 "./src/mcap/reader.js",
 "./src/mcap/run.js",
 "./src/render/engine.js",
 "./src/render/panels.js",
 "./src/render/theme.js",
 "./src/render-tab.js",
 "./src/templates.js",
 "./templates/manifest.json",
 "./templates/showcase/panels/camera.json",
 "./templates/showcase/panels/cones.json",
 "./templates/showcase/panels/distance.json",
 "./templates/showcase/panels/header.json",
 "./templates/showcase/panels/lap.json",
 "./templates/showcase/panels/map.json",
 "./templates/showcase/panels/perception.json",
 "./templates/showcase/panels/pose.json",
 "./templates/showcase/panels/progress.json",
 "./templates/showcase/panels/speed-dial.json",
 "./templates/showcase/panels/steering.json",
 "./templates/showcase/panels/wheel-speeds.json",
 "./templates/showcase/template.json",
 "./templates/showcase/theme.json",
 "./templates/social/panels/camera.json",
 "./templates/social/panels/cones.json",
 "./templates/social/panels/credit.json",
 "./templates/social/panels/distance.json",
 "./templates/social/panels/header.json",
 "./templates/social/panels/lap.json",
 "./templates/social/panels/map.json",
 "./templates/social/panels/progress.json",
 "./templates/social/panels/speed-dial.json",
 "./templates/social/panels/steering.json",
 "./templates/social/template.json",
 "./templates/social/theme.json",
 "./token-check.html",
 "./vendor/buffer-shim.js",
 "./vendor/bundle.js",
 "./vendor/entry.js",
 "./vendor/node-stub.js",
 "./vendor/wasm-zstd.wasm",
 "./wasm-zstd.wasm",
 "./"
];
self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("fetch", (e) => {
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) return; // GitLab templates always go to the network
  e.respondWith(fetch(e.request).catch(() => caches.match(e.request).then((r) => r ?? caches.match("./index.html"))));
});
